name: Auto Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  gh_pages:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: "Install Dependencies"
        run: yarn
      - name: "Build"
        run: yarn build
        env:
          PUBLIC_URL: './our-call'
      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: ${{ github.event.head_commit.message }}
